In [2]:
import numpy

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

matrix=np.random.rand(2,2)
print(matrix)

[[0.72281264 0.87078446]
 [0.50033246 0.57496631]]


In [ ]:
#Create a NumPy array containing the numbers from 10 to 50. Display:
#The array
#Number of elements
#Shape
#Dimension
#Data type
arr1=np.arange(10,51)
print(arr1)
print("Number of elements:", arr1.size)
print("Shape:", arr1.shape)
print("Dimension:", arr1.ndim)
print("Data type:", arr1.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [ ]:
#Using NumPy, create:
#A 1D array containing 10 zeros
#A 3 × 3 array containing ones
#A 4 × 4 identity matrix
#An array containing numbers from 5 to 50 with a step size of 5.
arr_zeros = np.zeros(10, dtype=int) 
print("1D array of 10 zeros:\n", arr_zeros)
arr_ones = np.ones((3, 3), dtype=int)
print("3x3 array of ones:\n", arr_ones)
arr_identity = np.eye(4, dtype=int)
print("4x4 identity matrix:\n", arr_identity)
arr_range = np.arange(5, 51, 5, dtype=int)
print("Array from 5 to 50 with step size 5:\n", arr_range)


1D array of 10 zeros:
 [0 0 0 0 0 0 0 0 0 0]
3x3 array of ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
4x4 identity matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Array from 5 to 50 with step size 5:
 [ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
#Create an array containing numbers from 1 to 24. Reshape it into:
# 4 × 6
# 6 × 4
# 2 × 3 × 4
# Display the shape and ndim of each result.

arr2=np.arange(1,25)
arr3=np.reshape(arr2, (4,6))
print(arr3)
print("Shape of array:",arr3.shape)
print("Dimension of array:",arr3.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape of array: (4, 6)
Dimension of array: 2


In [27]:
arr4=np.reshape(arr2,(6,4))
print(arr4)
print("Shape of array:",arr4.shape)
print("Dimension of array:",arr4.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape of array: (6, 4)
Dimension of array: 2


In [28]:
arr2=np.reshape(arr2,(2,3,4))
print(arr2)
print("Shape of array:",arr2.shape)
print("Dimension of array:",arr2.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape of array: (2, 3, 4)
Dimension of array: 3


In [ ]:
#Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:
#First element
#Last element
#Third element
#First four elements
#Last three elements
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0],'or',marks[:-7],)
print(marks[-1],'or',marks[7:])
print(marks[2],'or',marks[2:3])
print(marks[0:4],'or',marks[:4],'or',marks[:-4])
print(marks[5:],'or',marks[-3:])

78 or [78]
81 or [81]
92 or [92]
[78 85 92 67] or [78 85 92 67] or [78 85 92 67]
[73 95 81] or [73 95 81]


In [ ]:
#Create:
#a = np.array([10, 20, 30, 40, 50])
#b = np.array([5, 10, 15, 20, 25])
#Calculate:
#a + b
#a - b
#a * b
#a / b
#Square of every element in a

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print("a+b:", a+b)
print("a-b:", a-b)
print("a*b:", a*b)
print("a/b:", a/b)
print("a**2:", a**2)

a+b: [15 30 45 60 75]
a-b: [ 5 10 15 20 25]
a*b: [  50  200  450  800 1250]
a/b: [2. 2. 2. 2. 2.]
a**2: [ 100  400  900 1600 2500]


In [52]:
#Given:
#salary = np.array([25000, 32000, 28000, 45000,
 #                  50000, 38000, 42000, 30000])
#Find:

#Total salary
#Average salary
#Highest salary
#Lowest salary
#Median salary
#Standard deviation
salary = np.array([25000, 32000, 28000, 45000,
                  50000, 38000, 42000, 30000])
print("Total salary:", np.sum(salary))
print("Average salary:", np.mean(salary))
print("Highest salary:", np.max(salary))
print("Lowest salary:", np.min(salary))
print("Median salary:", np.median(salary))
print("Standard deviation:", np.std(salary))

Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard deviation: 8317.902379807063


In [55]:
#Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:
#Marks greater than 75
#Marks between 50 and 80
#Number of students who scored below 50
#Percentage of students who scored 60 or above
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
print("Marks > 75:", marks[marks > 75])
print("Marks btwn 50 and 80:", marks[(marks >= 50) & (marks <= 80)])
print("No.of students scored below 50:", np.sum(marks < 50))
print("Percentage of students scored 60 or greater:", np.mean(marks >= 60) * 100)


Marks > 75: [78 89 90 76 84]
Marks btwn 50 and 80: [78 67 55 76]
No.of students scored below 50: 3
Percentage of students scored 60 or greater: 60.0


In [56]:
#The following array contains marks of four students in three subjects:
#marks = np.array([
 #   [80, 75, 90],
  #  [65, 70, 72],
   # [88, 92, 85],
    #[55, 60, 58]])
#Calculate:
#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])
print("Total marks of each student:", np.sum(marks, axis=1))
print("Average marks of each student:", np.mean(marks, axis=1))
print("Average marks in each subject:", np.mean(marks, axis=0))
print("Student with the highest total:", np.argmax(np.sum(marks, axis=1)))
print("Highest mark in each subject:", np.max(marks, axis=0))

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with the highest total: 2
Highest mark in each subject: [88 92 90]


In [ ]:
#11. Create:
#A = np.array([
 #   [1, 2],
  #  [3, 4]])
#B = np.array([
 #   [5, 6],
  #  [7, 8]])
#Perform:
#Matrix addition
#Element-wise multiplication
#Matrix multiplication
#Transpose of A.
#explain the difference between:
#A * B and A @ B
A = np.array([
    [1, 2],
    [3, 4]])
B = np.array([
    [5, 6],
    [7, 8]])
print("Matrix addition:\n", A + B)
print("Element-wise multiplication:\n", A * B)  
print("Matrix multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)
print("A * B is element-wise multiplication, while A @ B is matrix multiplication.")

Matrix addition:
 [[ 6  8]
 [10 12]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
