In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
data=pd.read_csv(r"data\Data - Data.csv")
dataset=data

In [4]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [5]:
dataset.head()


,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [9]:
dataset.shape


(10, 4)

In [11]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [12]:
dataset.describe()


,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [13]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [15]:
dataset.duplicated().sum()

np.int64(0)

In [21]:
dataset
X=dataset.iloc[::, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
y=dataset.iloc[:, 3].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [35]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])
Z=X
Z

array([[1, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 40.0,
        63777.77777777778],
       [1, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 38.77777777777778,
        52000.0],
       [1, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [1, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]],
      dtype=object)

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:, 0]=labelencoder_X.fit_transform(X[:, 0])
print(X)

[[1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [33]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder="passthrough")
X=ct.fit_transform(X)
X.astype(int)

array([[    1,     0,     1,     0,     1,     0,     1,     0,     0,
           44, 72000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           27, 48000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           30, 54000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           38, 61000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           40, 63777],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           35, 58000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           38, 52000],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           48, 79000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           50, 83000],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           37, 67000]])

In [36]:
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [38]:
x_test.astype(int)

array([[    0,     1,     0,     1,     0,     1,     0,     1,     0,
           30, 54000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           50, 83000]])

In [41]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
x_train=sc_X.fit_transform(x_train)
x_test=sc_X.transform(x_test)

In [42]:
x_test

array([[-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        ,  2.64575131, -0.77459667, -1.45882927,
        -0.90166297],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        ,  2.64575131, -0.77459667,  1.98496442,
         2.13981082]])