In [2]:
import numpy

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

matrix=np.random.rand(2,2)
print(matrix)

[[0.72281264 0.87078446]
 [0.50033246 0.57496631]]


In [ ]:
#Create a NumPy array containing the numbers from 10 to 50. Display:
#The array
#Number of elements
#Shape
#Dimension
#Data type
arr1=np.arange(10,51)
print(arr1)
print("Number of elements:", arr1.size)
print("Shape:", arr1.shape)
print("Dimension:", arr1.ndim)
print("Data type:", arr1.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [ ]:
#Using NumPy, create:
#A 1D array containing 10 zeros
#A 3 × 3 array containing ones
#A 4 × 4 identity matrix
#An array containing numbers from 5 to 50 with a step size of 5.
arr_zeros = np.zeros(10, dtype=int) 
print("1D array of 10 zeros:\n", arr_zeros)
arr_ones = np.ones((3, 3), dtype=int)
print("3x3 array of ones:\n", arr_ones)
arr_identity = np.eye(4, dtype=int)
print("4x4 identity matrix:\n", arr_identity)
arr_range = np.arange(5, 51, 5, dtype=int)
print("Array from 5 to 50 with step size 5:\n", arr_range)


1D array of 10 zeros:
 [0 0 0 0 0 0 0 0 0 0]
3x3 array of ones:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
4x4 identity matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Array from 5 to 50 with step size 5:
 [ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
#Create an array containing numbers from 1 to 24. Reshape it into:
# 4 × 6
# 6 × 4
# 2 × 3 × 4
# Display the shape and ndim of each result.

arr2=np.arange(1,25)
arr3=np.reshape(arr2, (4,6))
print(arr3)
print("Shape of array:",arr3.shape)
print("Dimension of array:",arr3.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape of array: (4, 6)
Dimension of array: 2


In [27]:
arr4=np.reshape(arr2,(6,4))
print(arr4)
print("Shape of array:",arr4.shape)
print("Dimension of array:",arr4.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape of array: (6, 4)
Dimension of array: 2


In [28]:
arr2=np.reshape(arr2,(2,3,4))
print(arr2)
print("Shape of array:",arr2.shape)
print("Dimension of array:",arr2.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape of array: (2, 3, 4)
Dimension of array: 3


In [ ]:
#Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:
#First element
#Last element
#Third element
#First four elements
#Last three elements
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print(marks[0],'or',marks[:-7],)
print(marks[-1],'or',marks[7:])
print(marks[2],'or',marks[2:3])
print(marks[0:4],'or',marks[:4],'or',marks[:-4])
print(marks[5:],'or',marks[-3:])

78 or [78]
81 or [81]
92 or [92]
[78 85 92 67] or [78 85 92 67] or [78 85 92 67]
[73 95 81] or [73 95 81]


In [ ]:
#Create:
#a = np.array([10, 20, 30, 40, 50])
#b = np.array([5, 10, 15, 20, 25])
#Calculate:
#a + b
#a - b
#a * b
#a / b
#Square of every element in a

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print("a+b:", a+b)
print("a-b:", a-b)
print("a*b:", a*b)
print("a/b:", a/b)
print("a**2:", a**2)

a+b: [15 30 45 60 75]
a-b: [ 5 10 15 20 25]
a*b: [  50  200  450  800 1250]
a/b: [2. 2. 2. 2. 2.]
a**2: [ 100  400  900 1600 2500]


In [52]:
#Given:
#salary = np.array([25000, 32000, 28000, 45000,
 #                  50000, 38000, 42000, 30000])
#Find:

#Total salary
#Average salary
#Highest salary
#Lowest salary
#Median salary
#Standard deviation
salary = np.array([25000, 32000, 28000, 45000,
                  50000, 38000, 42000, 30000])
print("Total salary:", np.sum(salary))
print("Average salary:", np.mean(salary))
print("Highest salary:", np.max(salary))
print("Lowest salary:", np.min(salary))
print("Median salary:", np.median(salary))
print("Standard deviation:", np.std(salary))

Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard deviation: 8317.902379807063


In [55]:
#Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
#Using NumPy boolean indexing, find:
#Marks greater than 75
#Marks between 50 and 80
#Number of students who scored below 50
#Percentage of students who scored 60 or above
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
print("Marks > 75:", marks[marks > 75])
print("Marks btwn 50 and 80:", marks[(marks >= 50) & (marks <= 80)])
print("No.of students scored below 50:", np.sum(marks < 50))
print("Percentage of students scored 60 or greater:", np.mean(marks >= 60) * 100)


Marks > 75: [78 89 90 76 84]
Marks btwn 50 and 80: [78 67 55 76]
No.of students scored below 50: 3
Percentage of students scored 60 or greater: 60.0


In [56]:
#The following array contains marks of four students in three subjects:
#marks = np.array([
 #   [80, 75, 90],
  #  [65, 70, 72],
   # [88, 92, 85],
    #[55, 60, 58]])
#Calculate:
#Total marks of each student
#Average marks of each student
#Average marks in each subject
#Student with the highest total
#Highest mark in each subject.
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])
print("Total marks of each student:", np.sum(marks, axis=1))
print("Average marks of each student:", np.mean(marks, axis=1))
print("Average marks in each subject:", np.mean(marks, axis=0))
print("Student with the highest total:", np.argmax(np.sum(marks, axis=1)))
print("Highest mark in each subject:", np.max(marks, axis=0))

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with the highest total: 2
Highest mark in each subject: [88 92 90]


In [ ]:
#11. Create:
#A = np.array([
 #   [1, 2],
  #  [3, 4]])
#B = np.array([
 #   [5, 6],
  #  [7, 8]])
#Perform:
#Matrix addition
#Element-wise multiplication
#Matrix multiplication
#Transpose of A.
#explain the difference between:
#A * B and A @ B
A = np.array([
    [1, 2],
    [3, 4]])
B = np.array([
    [5, 6],
    [7, 8]])
print("Matrix addition:\n", A + B)
print("Element-wise multiplication:\n", A * B)  
print("Matrix multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)
print("A * B is element-wise multiplication, while A @ B is matrix multiplication.")

Matrix addition:
 [[ 6  8]
 [10 12]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]


In [2]:
#12. Daily temperatures for two weeks are:
#temperature = np.array([
 #   31, 32, 33, 35, 36, 34, 32,
  #  30, 29, 31, 33, 35, 37, 36])
#Find:
#Mean temperature
#Maximum and minimum temperatures
#Number of days above the average temperature
#Temperatures greater than 34°C
#Difference between maximum and minimum
#Standard deviation
import numpy as np
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])
print("Mean temperature:", np.mean(temperature))
print("Max Temp:", np.max(temperature))
print("Min Temp:", np.min(temperature))
print("No.of days above avg:", np.sum(temperature > np.mean(temperature)))
print("Temperatures greater than 34°C:", temperature[temperature > 34])
print("Difference between max and min:", np.max(temperature) - np.min(temperature))
print("Standard deviation:", np.std(temperature))

Mean temperature: 33.142857142857146
Max Temp: 37
Min Temp: 29
No.of days above avg: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between max and min: 8
Standard deviation: 2.356060357495806


In [3]:
#13. Monthly sales of a company are:
"""sales = np.array([
   12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

Determine:

Total annual sales
Average monthly sales
Month with the highest sales
Month with the lowest sales
Number of months with sales above ₹20,000
Percentage increase from January to December"""
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])
print("Total annual sales:",np.sum(sales))
print("Avg monthly sales:",np.mean(sales))
print("Month with highest sales:", np.argmax(sales) + 1)
print("Month with lowest sales:", np.argmin(sales) + 1)
print("No.of months with sales above ₹20,000:", np.sum(sales > 20000))
percentage_increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Percentage increase from January to December:", percentage_increase)

Total annual sales: 240000
Avg monthly sales: 20000.0
Month with highest sales: 12
Month with lowest sales: 1
No.of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33333333333331


In [7]:
"""Consider marks of five students in four subjects:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]])
Write a NumPy program that calculates:
Total marks of every student
Average of every student
Average mark for every subject
Highest-scoring student
Lowest-scoring student
Students whose average is greater than 80
Overall class average
Then assign a performance category based on average:
|  Average | Category          |
| -------: | ----------------- |
|     ≥ 85 | Excellent         |
| 70–84.99 | Good              |
| 50–69.99 | Average           |
|     < 50 | Needs Improvement |

Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.
"""
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]])
print("Total marks of every student:", np.sum(marks, axis=1))
print("Average of every student:", np.mean(marks, axis=1))
print("Average mark for every subject:", np.mean(marks, axis=0))
print("Highest-scoring student:", np.argmax(np.sum(marks, axis=1)) + 1)
print("Lowest-scoring student:", np.argmin(np.sum(marks, axis=1)) + 1)
print("Students whose average is greater than 80:", np.sum(np.mean(marks, axis=1) > 80))
print("Overall class average:", np.mean(np.mean(marks, axis=1)))
print("Performance categories:")
average_scores = np.mean(marks, axis=1)
categories = np.select(
    [average_scores >= 85, average_scores >= 70, average_scores < 50],
    ['Excellent', 'Good', 'Needs Improvement'],
    default='Average'
)
print(categories)

Total marks of every student: [341 275 366 235 316]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject: [74.  75.6 79.4 77.6]
Highest-scoring student: 3
Lowest-scoring student: 4
Students whose average is greater than 80: 2
Overall class average: 76.65
Performance categories:
['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [15]:
#15. Generate 20 random integers between 1 and 100
random_integers = np.random.randint(1, 101, size=20)
print("Random integers:", random_integers)

Random integers: [13 93 93 79 86 17 99 51 26 86  3 70 25 28 95 48 28 62 31 56]


In [16]:
#16. Find all even numbers from the generated array.
even_numbers = random_integers[random_integers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [86 26 86 70 28 48 28 62 56]


In [17]:
#17. Replace values below 50 with 0.
modified_array = random_integers.copy()
modified_array[modified_array < 50] = 0
print("Modified array:", modified_array)

Modified array: [ 0 93 93 79 86  0 99 51  0 86  0 70  0  0 95  0  0 62  0 56]


In [18]:
#18. Sort the array in ascending and descending order.
ascending_order = np.sort(random_integers)
descending_order = np.sort(random_integers)[::-1]
print("Ascending order:", ascending_order)
print("Descending order:", descending_order)

Ascending order: [ 3 13 17 25 26 28 28 31 48 51 56 62 70 79 86 86 93 93 95 99]
Descending order: [99 95 93 93 86 86 79 70 62 56 51 48 31 28 28 26 25 17 13  3]


In [26]:
#19. Find unique values and their frequencies.
unique_values, frequencies = np.unique(random_integers, return_counts=True)
values = map(lambda x, y: f"{x}:{y}", unique_values, frequencies)
print("Unique values: Frequencies")
print("\n".join(values))

Unique values: Frequencies
3:1
13:1
17:1
25:1
26:1
28:2
31:1
48:1
51:1
56:1
62:1
70:1
79:1
86:2
93:2
95:1
99:1


In [27]:
#20. Create a 5 × 5 random matrix and calculate row-wise and column-wise means.
random_matrix = np.random.randint(1, 101, size=(5, 5))
print("Random 5x5 matrix:\n", random_matrix)
print("Row-wise means:", np.mean(random_matrix, axis=1))
print("Column-wise means:", np.mean(random_matrix, axis=0))

Random 5x5 matrix:
 [[32 62 21 62 80]
 [ 9 85 46 41  8]
 [85 79 93 13 29]
 [43 59 55 30 21]
 [39 44 49 44 82]]
Row-wise means: [51.4 37.8 59.8 41.6 51.6]
Column-wise means: [41.6 65.8 52.8 38.  44. ]


In [30]:
#21. Take your own example to normalize an array.
array = np.array([1, 2, 3, 4, 5])
normalized_array = (array - np.min(array)) / (np.max(array) - np.min(array))
print("Original array:", array)
print("Normalized array:", normalized_array)

Original array: [1 2 3 4 5]
Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [29]:
#22. use your own data to standardize an array. 
array = np.array([1, 2, 3, 4, 5])
standardized_array = (array - np.mean(array)) / np.std(array)
print("Original array:", array) 
print("Standardized array:", standardized_array)


Original array: [1 2 3 4 5]
Standardized array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
#23. Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.
exam_marks = np.random.randint(0, 101, size=100)
print("Exam marks:\n", np.reshape(exam_marks, (10, 10)))  
print("Number of students with marks 0-39:", np.sum((exam_marks >= 0) & (exam_marks <= 39)))
print("Number of students with marks 40-59:", np.sum((exam_marks >= 40) & (exam_marks <= 59)))
print("Number of students with marks 60-79:", np.sum((exam_marks >= 60) & (exam_marks <= 79)))
print("Number of students with marks 80-100:", np.sum((exam_marks >= 80) & (exam_marks <= 100)))


Exam marks:
 [[ 65  12  64  17  64  23  70  14  98  76]
 [ 88  79  32  64  89  68  17  26  27  42]
 [ 44  82  69  65   2  94  82  30  61  71]
 [ 26  52  24  74  33  50  98  16  24  90]
 [ 95  33  54  55  62   6  42  40  40  14]
 [ 51   5   6   3  14  71  71  82  59  20]
 [ 18  19  20  74  90  68  90  69  28  70]
 [ 40  39  71  96  30  69  94  42  56 100]
 [ 77  18  44  32  94  57  19  91  87  38]
 [ 63  98  82  50  44  33  34  52  13  55]]
Number of students with marks 0-39: 36
Number of students with marks 40-59: 20
Number of students with marks 60-79: 24
Number of students with marks 80-100: 20


In [36]:
#24. Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.


# Python list
import time
list1 = list(range(1, 1000001))
list2 = list(range(1, 1000001))
start_time = time.time()
result_list = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
print("Time taken by Python list:", end_time - start_time)
# NumPy array
array1 = np.arange(1, 1000001)
array2 = np.arange(1, 1000001)
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print("Time taken by NumPy array:", end_time - start_time)

Time taken by Python list: 0.03346514701843262
Time taken by NumPy array: 0.003879547119140625
