In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv(r"data\Data - Data.csv")
dataset=data

In [3]:
dataset

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [5]:
dataset.head()


,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


In [9]:
dataset.shape


(10, 4)

In [11]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='str')

In [12]:
dataset.describe()


,Age,Salary
count,9.000000,9.000000
mean,38.777778,63777.777778
std,7.693793,12265.579662
min,27.000000,48000.000000
25%,35.000000,54000.000000
50%,38.000000,61000.000000
75%,44.000000,72000.000000
max,50.000000,83000.000000


In [4]:
dataset.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
dataset.duplicated().sum()

np.int64(0)

In [6]:
dataset
X=dataset.iloc[::, :-1].values
X

array([[15624510, 'Male', 19, 19000],
       [15810944, 'Male', 35, 20000],
       [15668575, 'Female', 26, 43000],
       ...,
       [15654296, 'Female', 50, 20000],
       [15755018, 'Male', 36, 33000],
       [15594041, 'Female', 49, 36000]], shape=(400, 4), dtype=object)

In [7]:
y=dataset.iloc[:, 3].values
y

array([ 19000,  20000,  43000,  57000,  76000,  58000,  84000, 150000,
        33000,  65000,  80000,  52000,  86000,  18000,  82000,  80000,
        25000,  26000,  28000,  29000,  22000,  49000,  41000,  22000,
        23000,  20000,  28000,  30000,  43000,  18000,  74000, 137000,
        16000,  44000,  90000,  27000,  28000,  49000,  72000,  31000,
        17000,  51000, 108000,  15000,  84000,  20000,  79000,  54000,
       135000,  89000,  32000,  44000,  83000,  23000,  58000,  55000,
        48000,  79000,  18000, 117000,  20000,  87000,  66000, 120000,
        83000,  58000,  19000,  82000,  63000,  68000,  80000,  27000,
        23000, 113000,  18000, 112000,  52000,  27000,  87000,  17000,
        80000,  42000,  49000,  88000,  62000, 118000,  55000,  85000,
        81000,  50000,  81000, 116000,  15000,  28000,  83000,  44000,
        25000, 123000,  73000,  37000,  88000,  59000,  86000, 149000,
        21000,  72000,  35000,  89000,  86000,  80000,  71000,  71000,
      

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(X[:, 1:3])
X[:, 1:3]=imputer.transform(X[:, 1:3])
Z=X
Z

ValueError: Cannot use mean strategy with non-numeric data:
could not convert string to float: 'Male'

In [34]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:, 0]=labelencoder_X.fit_transform(X[:, 0])
print(X)

[[1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [33]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder="passthrough")
X=ct.fit_transform(X)
X.astype(int)

array([[    1,     0,     1,     0,     1,     0,     1,     0,     0,
           44, 72000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           27, 48000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           30, 54000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           38, 61000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           40, 63777],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           35, 58000],
       [    0,     1,     0,     1,     0,     1,     0,     0,     1,
           38, 52000],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           48, 79000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           50, 83000],
       [    1,     0,     1,     0,     1,     0,     1,     0,     0,
           37, 67000]])

In [36]:
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [38]:
x_test.astype(int)

array([[    0,     1,     0,     1,     0,     1,     0,     1,     0,
           30, 54000],
       [    0,     1,     0,     1,     0,     1,     0,     1,     0,
           50, 83000]])

In [41]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
x_train=sc_X.fit_transform(x_train)
x_test=sc_X.transform(x_test)

In [42]:
x_test

array([[-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        ,  2.64575131, -0.77459667, -1.45882927,
        -0.90166297],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         1.        , -1.        ,  2.64575131, -0.77459667,  1.98496442,
         2.13981082]])